baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Cloud Native Developer Tools"

theme = ["toolsmap"]
pluralizeListTitles = "false"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1